/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab.pkg2;

import java.awt.GridLayout;
import static java.lang.Math.pow;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ffeki
 */
public class Main extends javax.swing.JFrame {

    private javax.swing.JTextField[] text = new JTextField[25];
    int matris[][] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}, {1, 2, 3}};
    
    public Main() {
        initComponents();
        jL_M.setVisible(false);
        jL_N.setVisible(false);
        
        MatrixGUI(4, 3, matris, jPanel1); //ters :(

    }

    void MatrixGUI(int rows, int column, int[][] matrix, JPanel jp) {
        jp.setLayout(new GridLayout(0, column, 20, 20));
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < column; j++) {
                
                text[i] = new javax.swing.JTextField();
                text[i].setText(""+matrix[i][j]);
                jp.add(text[i]);

            }   
            
            jp.revalidate();
            jp.repaint();

        }
    }

    int[][] Multiplication(int[][] m, int[][] m2) {
        int[][] matris = new int[m.length][m2[0].length];

        for (int i = 0; i < m.length; i++) {
            for (int j = 0; j < m2[0].length; j++) {
                int tmp = 0;
                for (int k = 0; k < m[0].length; k++) {
                    tmp += m[i][k] * m2[k][j];

                }
                matris[i][j] = tmp;
                System.out.print(matris[i][j] + " ");
            }
            System.out.println("");

        }

        return matris;
    }

    int[][] Transpose(int[][] matris) {
        int[][] newMatris = new int[matris[0].length][matris.length];
        for (int i = 0; i < matris.length; i++) {
            for (int j = 0; j < matris[0].length; j++) {
                newMatris[j][i] = matris[i][j];
            }
        }
        return newMatris;

    }

    void PrintMatrix(int[][] matrix) {
        for (int i = 0; i < matrix.length; i++) {
            for (int j = 0; j < matrix[0].length; j++) {
                System.out.print(matrix[i][j] + " ");
            }
            System.out.println();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Random = new javax.swing.JButton();
        jB_Manuel = new javax.swing.JButton();
        jL_M = new javax.swing.JLabel();
        jL_N = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_Random.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Random.setText("Rastgele");
        jB_Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RandomActionPerformed(evt);
            }
        });

        jB_Manuel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Manuel.setText("Manuel");
        jB_Manuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ManuelActionPerformed(evt);
            }
        });

        jL_M.setText("Pseudo Inverse = (A^t x A)^-1 x A^t");

        jL_N.setText("Pseudo Inverse = A^t x (A x A^t)^-1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jB_Random, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Manuel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_N, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_M, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(830, 830, 830))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Random, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Manuel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_N, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_M, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RandomActionPerformed
        // TODO add your handling code here:
        int rows, column;
        Random rand = new Random();
        rows = rand.nextInt(5) + 1;
        while (true) {
            column = rand.nextInt(5) + 1;
            if (column != rows) {
                break;
            }
        }

        int[][] matris = new int[rows][column];

        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < column; j++) {
                matris[i][j] = rand.nextInt(50);
                System.out.print(matris[i][j] + " ");
            }
            System.out.println("");

        }

        System.out.println(rows + " - " + column);

        if (rows > column) {
            jL_M.setVisible(true);
            jL_N.setVisible(false);
        } else {
            jL_M.setVisible(false);
            jL_N.setVisible(true);
        }

    }//GEN-LAST:event_jB_RandomActionPerformed

    private void jB_ManuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ManuelActionPerformed
        // TODO add your handling code here:
        int rows, column;

        while (true) {
            String r = JOptionPane.showInputDialog("Matris satır(rows) boyutu giriniz (1-5): ");
            String c = JOptionPane.showInputDialog("Matris sütun(column) boyutu giriniz (1-5): ");

            rows = Integer.parseInt(r);
            column = Integer.parseInt(c);

            if (rows > 0 && rows < 6 && column > 0 && column < 6 && column != rows) {

                //çalıştır
                System.out.println(rows + " - " + column);
                break;
            }
        }

        int[][] matris = new int[rows][column];
        int value;

        for (int i = 0; i < matris.length; i++) {
            for (int j = 0; j < matris[0].length; j++) {
                String tmp = JOptionPane.showInputDialog("Matris[" + i + "][" + j + "] elemanını giriniz: ");
                matris[i][j] = Integer.parseInt(tmp);
            }
        }

        if (rows > column) {
            jL_M.setVisible(true);
            jL_N.setVisible(false);
        } else {
            jL_M.setVisible(false);
            jL_N.setVisible(true);
        }

    }//GEN-LAST:event_jB_ManuelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Manuel;
    private javax.swing.JButton jB_Random;
    private javax.swing.JLabel jL_M;
    private javax.swing.JLabel jL_N;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
